---

# This workflow will do a clean install of all dependencies, cache/restore
# them, build the source code and run tests across different versions fo node.

name: Test CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20, 22]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci --timing
      - run: npm run lint
      - run: npm run build:debug
      - name: "Run tests"
        run: npm test
        env:
          NODE_OPTIONS: "--import=./register.js"
...
